imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@gaelicBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:
    app.path.product_images: ../web/uploads/images/products
    app.path.entrainement_images: ../web/entrainement
    app.path.sponsor_images: ../web/sponsor
    app.path.new_images: ../web/new
    app.path.media_images: ../web/media

    locale: fr


framework:
    templating:
            engines: ['twig']
    #esi: ~
    translator: { fallbacks: [ "fr" ] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: gaelicBundle\Entity\User
    from_email:
        address: "guillaume.plard@lapiscine.pro"
        sender_name: "guillaume"

#easy_admin:
#    entities:
#        # change the following to the namespaces of your own entities
#        - gaelicBundle\Entity\User
#        - gaelicBundle\Entity\Media
#        - gaelicBundle\Entity\News
#        - gaelicBundle\Entity\Sponsors
#        - gaelicBundle\Entity\Entrainement
#        - gaelicBundle\Entity\Contact

easy_admin:
    list_max_results: 20
    site_name: 'Burdigaela'
    design:
        brand_color: '#770808'
    entities:

        User:
            class: gaelicBundle\Entity\User
            label: 'Utilisateur'
            list:
              title: "changement d'utilisateur"

        Media:
            class: gaelicBundle\Entity\Media
            label: 'Media'
            list:
              title: "inserer un Média"
              fields: ['id',{ property: 'image', type: 'image', base_path: '%app.path.media_images%' }]
            form:
              fields:
                     - { type: 'tab', label: 'envoyer photo ', icon: 'camera' }
                     - { property: 'imageFile', type: 'vich_image' }



        News:
            class: gaelicBundle\Entity\News
            label: 'News'
            list:
                title: "Insérer une Actualité"
                fields: ['id', 'Titre', 'Contenu',{ property: 'image', type: 'image', base_path: '%app.path.new_images%' }]
            form:
                fields:
                       - { type: 'tab', label: 'enregistrement actualité', icon: 'newspaper-o' }
                       - titre
                       - Contenu
                       - { property: 'imageFile', type: 'vich_image' }



        Sponsors:
            class: gaelicBundle\Entity\Sponsors
            label: 'Sponsors'
            list:
              title: "Sponsoring"
              fields: ['id', 'Titre', 'Contenu',{ property: 'image', type: 'image', base_path: '%app.path.sponsor_images%' }]
            form:
              fields:
                     - { type: 'tab', label: 'Ajouter sponsors', icon: 'black-tie' }
                     - titre
                     - Contenu
                     - { property: 'imageFile', type: 'vich_image' }





        Entrainement:
            class: gaelicBundle\Entity\Entrainement
            label: 'Entrainement'
            list:
              title: "gestion des entrainements"
              fields: ['id', 'Titre', 'Contenu',{ property: 'image', type: 'image', base_path: '%app.path.entrainement_images%' }]

            form:
              fields:
                     - { type: 'tab', label: 'ajout lieu Entrainement', icon: 'dribbble' }
                     - titre
                     - Contenu
                     - { property: 'imageFile', type: 'vich_image' }

        Contact:
            class: gaelicBundle\Entity\Contact
            list:
              title: "Insérer un Contact"
              fields: ['id',{ property: 'sujet', label: 'sujet' },'Message',{ property: 'email', label: 'email' },{ property: 'nom', label: 'nom' },{ property: 'prenom', label: 'prenom' }]
            form:
              fields:
                     - { type: 'tab', label: 'Contact Information', icon: 'envelope-o' }
                     - sujet
                     - Message
                     - email
                     - nom
                     - prenom


        Image:
            class: gaelicBundle\Entity\Image
            help: 'Bienvenue sur la page de chargement'
            list:
              fields:
                   - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            show:
              fields:
                   - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            form:
              fields:
                   - { property: 'imageFile', type: 'vich_image' }






vich_uploader:
    db_driver: orm

    mappings:
            product_images:
                uri_prefix:      '%app.path.product_images%'
                upload_destination: '%kernel.root_dir%/../web%app.path.product_images%'

            entrainement_images:
                uri_prefix:      '%app.path.entrainement_images%'
                upload_destination: '%kernel.root_dir%/../web/entrainement%app.path.entrainement_images%'

            sponsor_images:
                uri_prefix:      '%app.path.sponsor_images%'
                upload_destination: '%kernel.root_dir%/../web/sponsor'

            new_images:
                uri_prefix:      '%app.path.new_images%'
                upload_destination: '%kernel.root_dir%/../web/new'

            media_images:
                uri_prefix:      '%app.path.media_images%'
                upload_destination: '%kernel.root_dir%/../web/media'








