<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBtmxhy8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBtmxhy8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBtmxhy8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBtmxhy8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBtmxhy8\appProdProjectContainer(array(
    'container.build_hash' => 'Btmxhy8',
    'container.build_id' => 'bcc5b267',
    'container.build_time' => 1532098764,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBtmxhy8');
