<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8nuaizt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8nuaizt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8nuaizt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8nuaizt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8nuaizt\appDevDebugProjectContainer(array(
    'container.build_hash' => '8nuaizt',
    'container.build_id' => '74530464',
    'container.build_time' => 1535039536,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8nuaizt');
