<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ufhgg7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ufhgg7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4ufhgg7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4ufhgg7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4ufhgg7\appDevDebugProjectContainer(array(
    'container.build_hash' => '4ufhgg7',
    'container.build_id' => '3fbe1374',
    'container.build_time' => 1534517618,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4ufhgg7');
